version: '3.9'
services:
 crdb1:
   image: cockroachdb/cockroach:latest
   container_name: crdb1
   hostname: crdb1
   ports:
     - "26257:26257"
     - "18080:8080"
   command: start-single-node --insecure --store=cockroach-data/crdb1 
   volumes:
     - "${PWD}/cockroach-data/crdb1:/cockroach/cockroach-data"
     - "${PWD}/scripts:/scripts"

